[package]
name = "Patika-MerkleTree-Assignment"
version = "0.1.0"
edition = "2021"

[lib]
name = "merklelib"
path = "src/lib.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sha2 = "0.10"
base64 = "0.13.0"
hex = "0.4.2"